### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by henrydaly** [biscuit-auth/biscuit-java#48]
I'm having trouble getting namespacing to work. Here's how I've written the fact:
```
biscuitBuilder.add_authority_fact("mynamespace:somefact(\"value\")");
```

And I received an error like so:
```
Error{input=':somefact("value")', message='opening parens not found'}
```

I also tried adding double backslashes, but that also seems to fail. The datalog reference on the biscuit [documentation](https://www.biscuitsec.org/docs/reference/datalog/) suggest that namespaces should work with a simple colon. Am I missing something?

**Comment by KannarFr** [comment]
@henrydaly namespacing is currently not supported by biscuit-java ATM.

**Comment by henrydaly** [comment]
@KannarFr thanks for the quick response! Any idea on timeline for when it might be supported? Alternatively, if it's not in the roadmap and the community wanted to add support, is there any assistance that could be provided as to what needs to be done?

**Comment by KannarFr** [comment]
@Geal does samples support namespaces?

**Comment by Geal** [comment]
it is supported in the [biscuit specification](https://github.com/biscuit-auth/biscuit/blob/master/SPECIFICATIONS.md#grammar) and it should be supported by the java version: https://github.com/CleverCloud/biscuit-java/blob/master/src/main/java/com/clevercloud/biscuit/token/builder/parser/Parser.java#L202
@henrydaly are you using the most recent version of biscuit-java?

**Comment by henrydaly** [comment]
I'm using version 2.2.0, the latest I believe
