### ISSUE TITLE
Remove vavr Option from public Biscuit.make method

### ISSUE THREAD

**Issue by KannarFr** [biscuit-auth/biscuit-java#66]
```java
Biscuit.make(args)
Biscuit.builder(args)
```

`args` has an `io.vavr.control.Option` field which is unpleasant to embed when using the library method.

We can convert it to `java.util.Optional` and/or undeprecated the method https://github.com/biscuit-auth/biscuit-java/blob/master/src/main/java/com/clevercloud/biscuit/token/Biscuit.java#L85. 

WDYT?

**Comment by KannarFr** [comment]
cc @divarvel @Geal @Korbik

**Comment by Geal** [comment]
java.util.Optional looks fine. I don't  remember why we went with vavr at the time. @Keruspe do you know?

**Comment by Keruspe** [comment]
Optional is sh*t, it's not Serializable and you shouldn't use it anywhere but in a getter signature basically, it's not there to hold any data, just as a type hint for one shot ops.

**Comment by divarvel** [comment]
on the one hand, java's optional is a poor substitute for a proper option type (deliberately so, it was not designed to be equivalent (as to why, it baffles me, but whatever)).

on the other hand, i see the merit in not exposing vavr specifics in a _library_ API. 

Anyway, all of that is of very little significance compared to other API considerations (easy whole-block parsing, **parameter interpolation**, full v3 blocks compliance)

**Comment by KannarFr** [comment]
Ok, thanks for all this feedback, so maybe the best option as a "Java convention" is to create two methods signatures: 
* one without the Option[X] argument ;
* one other with X argument.

?

**Comment by Geal** [comment]
oh, right, that was just for the presence or not of the root key id? Then yes, making two versions, one with arg, one without should be fine
